app:
    resource: '@AppBundle/Controller/'
    type: annotation

email_sender_send_email:
    path:     /send_email
    defaults: { _controller: "AppBundle:EmailSender:SendEmail" }

email_sender_send_email_ajax:
    path:     /send_email_ajax
    defaults: { _controller: "AppBundle:EmailSender:SendEmailAjax" }
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
